version: '2.0'
services:
  api:
    build: ./Backend/PublicApi
    ports:
    - "5001:80"
    volumes:
    - ./Backend/PublicApi/datafiles:/app/datafiles
  frontend:
    build: ./Client
    ports:
    - "5000:80"
