version: '3.1'
services:
  database:
    image: mongo:latest
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db
